### ISSUE TITLE
Third party tools

### ISSUE THREAD

**Issue by tbranyen** [bocoup/email#1]
- https://github.com/dachev/node-crontab
*Schedule and maintain jobs in Cron*
- https://github.com/strongloop/express
*Create Express-compat server*
- https://github.com/aws/aws-sdk-js
*Send email*

**Comment by tkellen** [comment]
:+1: Are you cool with using vagrant/ansible for testing/deployment? @cowboy has written a great template for single page apps that could easily be tweaked to support a dynamic site (ping @ajpiano for feedback as he just did this a day or two ago). It's here: http://github.com/bocoup/nest-applicants (under the deploy folder)

**Comment by tkellen** [comment]
Also, I'd like to open source this from the outset, there is nothing Bocoup-specific about this... you cool with that?

**Comment by tbranyen** [comment]
Yeah, I made the repository public to start, because I agree, nothing proprietary with what we're building here.

**Comment by tbranyen** [comment]
I've never used ansible before, but sure I'll look into that once I get the prototype working.

**Comment by cowboy** [comment]
@tbranyen if you have questions about my deploy workflow, just let me know.

**Comment by tbranyen** [comment]
Considering this: https://github.com/burningtree/uson to store metadata in Cron

**Comment by tbranyen** [comment]
Thanks @cowboy!

**Comment by bmac** [comment]
A while back I build a similar email service using https://github.com/Automattic/kue for scheduling and [mandrill](https://mandrill.com/) for email delivery.

**Comment by tbranyen** [comment]
@bmac that is a great looking alternative stack.  I'll be designing this API such that we can swap out for something else, if it turns out my idea is a fools errand.  Ideally the API wouldn't change by switching away from Cron.

**Comment by tafsiri** [comment]
@tbranyen are you still planning on using cron for this. I think i'm coming up to speed with the use cases for this system. But I wonder if using cron ties the schedule too much to a particular machine instance. Imagning this is deploy on AWS, what happens if the instance on which this crontab exists needs to be destroyed and remade? Would I lost any existing schedule?

**Comment by tbranyen** [comment]
@tafsiri we should be able to back up the state into a database if that becomes a requirement

**Comment by cowboy** [comment]
We need to invent **Cron:cloud:Cloud™**

**Comment by tbranyen** [comment]
Closing discussion
