### ISSUE TITLE
Better name?

### ISSUE THREAD

**Issue by tbranyen** [bocoup/email#6]
Some people just don't appreciate my creativity.

**Comment by jugglinmike** [comment]
"Edna"

**Comment by leobalter** [comment]
P.O.Bob

**Comment by tkellen** [comment]
inbox-filler

**Comment by Wilto** [comment]
gmail

wait

**Comment by tbranyen** [comment]
We have email.bocoup.com so we'll keep this awesome name! :tanabata_tree:
